use std::collections::{BTreeMap, BTreeSet};
use std::sync::Arc;

use serde::Deserializer as _;
use serde::de::{DeserializeOwned, MapAccess, SeqAccess, Visitor};
use serde_json::Value;

use crate::{
    AgentId, Digest, ErrorCode, EventEnvelope, EventTypeBinding, EvidenceRecord, IsolationScope,
    ProtocolLimitsRef, RunManifest, SchemaDocument, SchemaRef, SchemaSetManifest, SchemaSetRef,
    StreamId, TrustedValidationContext, ValidationError, canonical_json_bytes, digest_json,
    digest_schema,
};

type AdmittedSchemas = (
    BTreeMap<SchemaRef, Value>,
    BTreeMap<SchemaRef, Arc<jsonschema::Validator>>,
);

/// Fixed V1 limits. A kernel may select a stricter, separately versioned profile.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ProtocolLimitsV1;

impl ProtocolLimitsV1 {
    /// Digest of the canonical V1 limits profile published by RFC-0002.
    pub const DIGEST: &'static str =
        "sha256:75f04f5d173aa822efca55f8233c8e09e57a731ee3987b69bb8a86efcf35080f";
    /// Raw JSON transport ceiling before parsing.
    pub const RAW_RECORD_BYTES: usize = 1_048_576;
    /// Canonical semantic record ceiling.
    pub const RECORD_BYTES: usize = 1_048_576;
    /// Canonical payload ceiling.
    pub const PAYLOAD_BYTES: usize = 786_432;
    /// Decoded UTF-8 string ceiling.
    pub const STRING_BYTES: usize = 262_144;
    /// Root is depth one.
    pub const DEPTH: usize = 64;
    /// Per-array or per-object member ceiling.
    pub const COLLECTION: usize = 16_384;
    /// Maximum deterministic errors returned by a batch API.
    pub const ERRORS: usize = 32;
}

/// A value that passed protocol validation. Its field is private to prevent extension forgery.
#[derive(Clone, Debug, PartialEq)]
pub struct Validated<T>(T);

impl<T> Validated<T> {
    /// Borrows the validated value without granting kernel authorization.
    pub fn get(&self) -> &T {
        &self.0
    }

    /// Consumes the wrapper and returns the validated value.
    pub fn into_inner(self) -> T {
        self.0
    }
}

/// Event admitted through one exact registry variant and its payload schema.
#[derive(Clone, Debug, PartialEq)]
pub struct ValidatedEvent {
    envelope: EventEnvelope,
    variant_id: String,
}

impl ValidatedEvent {
    /// Returns the validated immutable envelope.
    pub fn envelope(&self) -> &EventEnvelope {
        &self.envelope
    }

    /// Returns the exact language-independent typed variant selected by the registry.
    pub fn variant_id(&self) -> &str {
        &self.variant_id
    }
}

/// Opaque Kernel capability required to admit a schema set.
#[derive(Debug)]
pub(crate) struct SchemaAdmissionAuthority {
    _private: (),
}

impl SchemaAdmissionAuthority {
    /// SHA-256 of the exact Draft 2020-12 root meta-schema embedded by jsonschema 0.50.0.
    pub const METASCHEMA_DIGEST: &'static str =
        "sha256:483c0526fdeb85e072d9cca4eee4ba7f1179d1ce89cb21c42b3c01296442f9e6";
    #[allow(dead_code)] // Consumed by the future in-crate kernel module; unit tests exercise it now.
    pub(crate) fn kernel_owned() -> Self {
        Self { _private: () }
    }
}

/// Immutable admitted schema set with event type bindings.
#[derive(Clone, Debug)]
pub struct SchemaSet {
    reference: SchemaSetRef,
    manifest: SchemaSetManifest,
    _documents: BTreeMap<SchemaRef, Value>,
    validators: BTreeMap<SchemaRef, Arc<jsonschema::Validator>>,
}

impl SchemaSet {
    /// Bootstraps only the exact schema set generated by this protocol release.
    pub fn bootstrap_initial(
        manifest: SchemaSetManifest,
        documents: Vec<SchemaDocument>,
        expected_reference: &SchemaSetRef,
    ) -> Result<Self, ValidationError> {
        let embedded = crate::generate_schema_bundle()?.reference;
        if &embedded != expected_reference {
            return Err(schema_error(
                "/manifest_digest",
                "initial schema set does not match the embedded trust root",
            ));
        }
        Self::admit(
            &SchemaAdmissionAuthority::kernel_owned(),
            manifest,
            documents,
            expected_reference,
        )
    }

    /// Admits a manifest only when its members are sorted, unique, and match the expected digest.
    pub(crate) fn admit(
        _authority: &SchemaAdmissionAuthority,
        manifest: SchemaSetManifest,
        documents: Vec<SchemaDocument>,
        expected_reference: &SchemaSetRef,
    ) -> Result<Self, ValidationError> {
        validate_manifest_order(&manifest)?;
        let (verified_documents, validators) = validate_schema_documents(&manifest, documents)?;
        if !manifest
            .schemas
            .contains(&expected_reference.manifest_schema_ref)
        {
            return Err(schema_error(
                "/manifest_schema_ref",
                "manifest schema is not a member",
            ));
        }
        let value = serde_json::to_value(&manifest)
            .map_err(|_| invariant("schema set serialization failed"))?;
        let actual = digest_json(
            "schema-set",
            &expected_reference.manifest_schema_ref,
            &value,
        )?;
        if actual != expected_reference.manifest_digest {
            return Err(ValidationError::new(
                ErrorCode::DigestMismatch,
                "/manifest_digest",
                "schema_set",
                "manifest digest mismatch",
            ));
        }
        Ok(Self {
            reference: expected_reference.clone(),
            manifest,
            _documents: verified_documents,
            validators,
        })
    }

    /// Returns the exact admitted schema-set reference.
    pub fn reference(&self) -> &SchemaSetRef {
        &self.reference
    }

    /// Returns true only for a complete member SchemaRef.
    pub fn contains(&self, schema: &SchemaRef) -> bool {
        self.manifest.schemas.binary_search(schema).is_ok()
    }

    fn event_binding(&self, envelope: &EventEnvelope) -> Option<&EventTypeBinding> {
        self.manifest.event_bindings.iter().find(|binding| {
            binding.event_type == envelope.event_type
                && binding.major == envelope.event_major
                && binding.minor == envelope.event_minor
        })
    }

    fn exact_schema(&self, schema_type: &str) -> Option<&SchemaRef> {
        let mut matches = self
            .manifest
            .schemas
            .iter()
            .filter(|schema| schema.r#type == schema_type);
        let first = matches.next()?;
        matches.next().is_none().then_some(first)
    }

    #[allow(dead_code)] // Consumed by the future in-crate kernel module; unit tests exercise it now.
    pub(crate) fn trusted_context(
        &self,
        scope: IsolationScope,
        actor: AgentId,
        target_stream: StreamId,
        protocol_limits_ref: ProtocolLimitsRef,
    ) -> TrustedValidationContext {
        TrustedValidationContext {
            scope,
            actor,
            target_stream,
            schema_set_ref: self.reference.clone(),
            protocol_limits_ref,
        }
    }

    /// Kernel-facing validation entry point; validation does not grant authorization/capability.
    pub fn validate_event_at_boundary(
        &self,
        envelope: EventEnvelope,
        expected_scope: IsolationScope,
        authenticated_actor: AgentId,
        target_stream: StreamId,
        protocol_limits_ref: ProtocolLimitsRef,
    ) -> Result<ValidatedEvent, Vec<ValidationError>> {
        let context = self.trusted_context(
            expected_scope,
            authenticated_actor,
            target_stream,
            protocol_limits_ref,
        );
        self.validate_event(envelope, &context)
    }

    /// Validates an event against the exact run context, registry binding, limits, and payload digest.
    pub fn validate_event(
        &self,
        envelope: EventEnvelope,
        context: &TrustedValidationContext,
    ) -> Result<ValidatedEvent, Vec<ValidationError>> {
        let mut errors = Vec::new();
        let mut selected_variant = None;
        if let Err(error) = validate_limits_ref(&context.protocol_limits_ref) {
            errors.push(error);
        }
        if let Ok(value) = serde_json::to_value(&envelope) {
            if let Err(error) = validate_value_limits(&value, ProtocolLimitsV1::RECORD_BYTES) {
                errors.push(error);
            }
        }
        if let Err(error) =
            validate_value_limits(&envelope.payload, ProtocolLimitsV1::PAYLOAD_BYTES)
        {
            errors.push(error);
        }
        if !errors.is_empty() {
            sort_and_truncate(&mut errors);
            return Err(errors);
        }
        if context.schema_set_ref != self.reference {
            errors.push(ValidationError::new(
                ErrorCode::SchemaMismatch,
                "/schema_set_ref",
                "trusted_context",
                "wrong schema set for run",
            ));
        }
        validate_scope(&envelope.scope, &context.scope, &mut errors);
        if envelope.actor != context.actor {
            errors.push(scope_error("/actor", "actor mismatch"));
        }
        if envelope.stream_id != context.target_stream {
            errors.push(scope_error("/stream_id", "stream mismatch"));
        }
        if envelope.run_id != context.scope.run_id {
            errors.push(scope_error("/run_id", "run mismatch"));
        }
        if envelope.schema_ref != self.manifest.event_envelope_schema_ref {
            errors.push(schema_error(
                "/schema_ref",
                "envelope schema is not the exact schema bound by this set",
            ));
        } else if let (Some(validator), Ok(value)) = (
            self.validators.get(&envelope.schema_ref),
            serde_json::to_value(&envelope),
        ) {
            validate_json_schema(validator, &value, "", &mut errors);
        }
        if !self.contains(&envelope.payload_schema_ref) {
            errors.push(schema_error(
                "/payload_schema_ref",
                "payload schema is not a set member",
            ));
        }
        match self.event_binding(&envelope) {
            Some(binding) if binding.payload_schema_ref == envelope.payload_schema_ref => {
                if binding.variant_id.is_empty() {
                    errors.push(ValidationError::new(
                        ErrorCode::EventTypeMismatch,
                        "/event_type",
                        "event_type_registry",
                        "typed variant identifier is empty",
                    ));
                }
                selected_variant = Some(binding.variant_id.clone());
                if let Some(validator) = self.validators.get(&binding.payload_schema_ref) {
                    validate_json_schema(validator, &envelope.payload, "/payload", &mut errors);
                } else {
                    errors.push(schema_error(
                        "/payload_schema_ref",
                        "payload schema document is unavailable",
                    ));
                }
            }
            _ => errors.push(ValidationError::new(
                ErrorCode::EventTypeMismatch,
                "/payload_schema_ref",
                "event_type_registry",
                "event type/version is not bound to payload schema",
            )),
        }
        if envelope.sequence.is_empty()
            || envelope.sequence == "0"
            || !is_decimal(&envelope.sequence)
        {
            errors.push(ValidationError::new(
                ErrorCode::InvariantViolation,
                "/sequence",
                "positive_decimal",
                "sequence must be positive canonical decimal",
            ));
        }
        if !is_canonical_timestamp(&envelope.occurred_at) {
            errors.push(ValidationError::new(
                ErrorCode::InvalidTimestamp,
                "/occurred_at",
                "utc_rfc3339_millis",
                "timestamp must use canonical UTC milliseconds",
            ));
        }
        match digest_json(
            "event-payload",
            &envelope.payload_schema_ref,
            &envelope.payload,
        ) {
            Ok(actual) if actual == envelope.payload_digest => {}
            _ => errors.push(ValidationError::new(
                ErrorCode::DigestMismatch,
                "/payload_digest",
                "event_payload",
                "payload digest mismatch",
            )),
        }
        sort_and_truncate(&mut errors);
        if errors.is_empty() {
            Ok(ValidatedEvent {
                envelope,
                variant_id: selected_variant.expect("successful binding selects a variant"),
            })
        } else {
            Err(errors)
        }
    }

    /// Validates a run manifest at the create-run boundary.
    pub fn validate_run_manifest(
        &self,
        manifest: RunManifest,
        expected_scope: &IsolationScope,
    ) -> Result<Validated<RunManifest>, Vec<ValidationError>> {
        let mut errors = Vec::new();
        validate_scope(&manifest.scope, expected_scope, &mut errors);
        if manifest.schema_set_ref != self.reference {
            errors.push(schema_error(
                "/schema_set_ref",
                "run manifest does not pin the admitted schema set",
            ));
        }
        if let Err(error) = validate_limits_ref(&manifest.protocol_limits_ref) {
            errors.push(error);
        }
        if self.exact_schema("run-manifest") != Some(&manifest.schema_ref) {
            errors.push(schema_error(
                "/schema_ref",
                "run manifest does not use the exact schema bound by this set",
            ));
        } else if let (Some(validator), Ok(value)) = (
            self.validators.get(&manifest.schema_ref),
            serde_json::to_value(&manifest),
        ) {
            validate_json_schema(validator, &value, "", &mut errors);
        }
        for role in [
            "task",
            "behavior",
            "workspace",
            "environment",
            "context_graph",
            "model_snapshot",
            "tool_set",
            "kernel",
        ] {
            if !manifest.revisions.contains_key(role) {
                errors.push(ValidationError::new(
                    ErrorCode::InvariantViolation,
                    &format!("/revisions/{role}"),
                    "run_manifest",
                    "required revision pin is missing",
                ));
            }
        }
        if manifest.revisions.len() != 8 {
            errors.push(ValidationError::new(
                ErrorCode::InvariantViolation,
                "/revisions",
                "run_manifest",
                "revision roles must equal the closed required set",
            ));
        }
        if let Err(error) = manifest.execution_mode.validate(&manifest.scope.run_id) {
            errors.push(error);
        }
        if let Ok(value) = serde_json::to_value(&manifest) {
            if let Err(error) = validate_value_limits(&value, ProtocolLimitsV1::RECORD_BYTES) {
                errors.push(error);
            }
        }
        sort_and_truncate(&mut errors);
        if errors.is_empty() {
            Ok(Validated(manifest))
        } else {
            Err(errors)
        }
    }

    /// Validates evidence scope, schema membership, time, and admission fields.
    pub fn validate_evidence(
        &self,
        evidence: EvidenceRecord,
        expected_scope: &IsolationScope,
        protocol_limits_ref: &ProtocolLimitsRef,
    ) -> Result<Validated<EvidenceRecord>, Vec<ValidationError>> {
        let mut errors = Vec::new();
        if let Err(error) = validate_limits_ref(protocol_limits_ref) {
            errors.push(error);
        }
        validate_scope(&evidence.scope, expected_scope, &mut errors);
        if self.exact_schema("evidence-record") != Some(&evidence.schema_ref) {
            errors.push(schema_error(
                "/schema_ref",
                "evidence does not use the exact schema bound by this set",
            ));
        } else if let (Some(validator), Ok(value)) = (
            self.validators.get(&evidence.schema_ref),
            serde_json::to_value(&evidence),
        ) {
            validate_json_schema(validator, &value, "", &mut errors);
        }
        if !is_canonical_timestamp(&evidence.observed_at) {
            errors.push(ValidationError::new(
                ErrorCode::InvalidTimestamp,
                "/observed_at",
                "utc_rfc3339_millis",
                "timestamp must use canonical UTC milliseconds",
            ));
        }
        for (path, value) in [
            ("/claim", &evidence.claim),
            ("/evidence_type", &evidence.evidence_type),
            ("/evidence_scope", &evidence.evidence_scope),
            ("/freshness", &evidence.freshness),
        ] {
            if value.is_empty() {
                errors.push(ValidationError::new(
                    ErrorCode::InvariantViolation,
                    path,
                    "evidence_record",
                    "field must not be empty",
                ));
            }
        }
        if let Ok(value) = serde_json::to_value(&evidence) {
            if let Err(error) = validate_value_limits(&value, ProtocolLimitsV1::RECORD_BYTES) {
                errors.push(error);
            }
        }
        sort_and_truncate(&mut errors);
        if errors.is_empty() {
            Ok(Validated(evidence))
        } else {
            Err(errors)
        }
    }
}

/// Parses a closed typed record and applies raw and canonical semantic limits.
pub fn parse_bounded<T: DeserializeOwned>(bytes: &[u8]) -> Result<T, ValidationError> {
    if bytes.len() > ProtocolLimitsV1::RAW_RECORD_BYTES {
        return Err(limit("raw record byte ceiling exceeded"));
    }
    let mut deserializer = serde_json::Deserializer::from_slice(bytes);
    let value = deserializer
        .deserialize_any(UniqueValueVisitor)
        .map_err(|_| {
            ValidationError::new(
                ErrorCode::InvalidJson,
                "",
                "json",
                "invalid JSON or duplicate object key",
            )
        })?;
    deserializer.end().map_err(|_| {
        ValidationError::new(ErrorCode::InvalidJson, "", "json", "trailing JSON data")
    })?;
    validate_value_limits(&value, ProtocolLimitsV1::RECORD_BYTES)?;
    serde_json::from_value(value).map_err(|_| {
        ValidationError::new(
            ErrorCode::InvalidJson,
            "",
            "typed_record",
            "record does not match closed typed contract",
        )
    })
}

fn validate_schema_documents(
    manifest: &SchemaSetManifest,
    documents: Vec<SchemaDocument>,
) -> Result<AdmittedSchemas, ValidationError> {
    if documents.len() != manifest.schemas.len() {
        return Err(schema_error(
            "/schemas",
            "member document count differs from manifest",
        ));
    }
    let mut verified = BTreeMap::new();
    let mut validators = BTreeMap::new();
    for document in documents {
        let schema_id = document
            .document
            .get("$id")
            .and_then(Value::as_str)
            .ok_or_else(|| schema_error("/$id", "schema document lacks ID"))?;
        if document.document.get("$schema").and_then(Value::as_str)
            != Some("https://json-schema.org/draft/2020-12/schema")
        {
            return Err(schema_error(
                "/$schema",
                "schema document does not use the fixed metaschema",
            ));
        }
        let _pinned_metaschema_digest = SchemaAdmissionAuthority::METASCHEMA_DIGEST;
        if !jsonschema::draft202012::meta::is_valid(&document.document) {
            return Err(schema_error(
                "",
                "schema document fails pinned Draft 2020-12 meta-validation",
            ));
        }
        let validator = jsonschema::options()
            .with_draft(jsonschema::Draft::Draft202012)
            .build(&document.document)
            .map_err(|_| schema_error("", "schema document fails Draft 2020-12 compilation"))?;
        let suffix = schema_id
            .strip_prefix("urn:pareto-harness:schema:")
            .ok_or_else(|| schema_error("/$id", "schema ID prefix mismatch"))?;
        let (name, version) = suffix
            .rsplit_once(':')
            .ok_or_else(|| schema_error("/$id", "schema ID lacks version"))?;
        let (major, minor) = version
            .split_once('.')
            .ok_or_else(|| schema_error("/$id", "schema ID lacks major/minor"))?;
        let digest = digest_schema(schema_id, &document.document)?;
        let reference = SchemaRef {
            r#type: name.to_owned(),
            major: major
                .parse()
                .map_err(|_| schema_error("/$id", "invalid major"))?,
            minor: minor
                .parse()
                .map_err(|_| schema_error("/$id", "invalid minor"))?,
            schema_digest: digest,
        };
        if manifest.schemas.binary_search(&reference).is_err() {
            return Err(schema_error(
                "/$id",
                "schema bytes do not match a manifest member",
            ));
        }
        if verified
            .insert(reference.clone(), document.document)
            .is_some()
        {
            return Err(schema_error("/$id", "duplicate schema document"));
        }
        validators.insert(reference, Arc::new(validator));
    }
    Ok((verified, validators))
}

fn validate_json_schema(
    validator: &jsonschema::Validator,
    instance: &Value,
    path: &str,
    errors: &mut Vec<ValidationError>,
) {
    for error in validator.iter_errors(instance) {
        let suffix = error.instance_path().as_str();
        errors.push(schema_error(
            &format!("{path}{suffix}"),
            "payload does not match admitted Draft 2020-12 schema",
        ));
    }
}

fn validate_manifest_order(manifest: &SchemaSetManifest) -> Result<(), ValidationError> {
    if !manifest.schemas.windows(2).all(|pair| pair[0] < pair[1]) {
        return Err(schema_error(
            "/schemas",
            "schemas must be strictly sorted and unique",
        ));
    }
    let mut ids = BTreeSet::new();
    for schema in &manifest.schemas {
        let id = format!("{}:{}.{}", schema.r#type, schema.major, schema.minor);
        if !ids.insert(id) {
            return Err(schema_error("/schemas", "duplicate schema identity"));
        }
    }
    if !manifest.event_bindings.windows(2).all(|pair| {
        (&pair[0].event_type, pair[0].major, pair[0].minor)
            < (&pair[1].event_type, pair[1].major, pair[1].minor)
    }) {
        return Err(schema_error(
            "/event_bindings",
            "event bindings must be strictly sorted and unique",
        ));
    }
    if manifest.event_bindings.iter().any(|binding| {
        manifest
            .schemas
            .binary_search(&binding.payload_schema_ref)
            .is_err()
    }) {
        return Err(schema_error(
            "/event_bindings",
            "event binding references a non-member schema",
        ));
    }
    if manifest
        .schemas
        .binary_search(&manifest.event_envelope_schema_ref)
        .is_err()
        || manifest.event_envelope_schema_ref.r#type != "event-envelope"
    {
        return Err(schema_error(
            "/event_envelope_schema_ref",
            "exact event envelope schema must be a set member",
        ));
    }
    Ok(())
}

fn validate_scope(
    actual: &IsolationScope,
    expected: &IsolationScope,
    errors: &mut Vec<ValidationError>,
) {
    if actual.tenant_id != expected.tenant_id {
        errors.push(scope_error("/scope/tenant_id", "tenant mismatch"));
    }
    if actual.user_id != expected.user_id {
        errors.push(scope_error(
            "/scope/user_id",
            "user presence or value mismatch",
        ));
    }
    if actual.workspace_id != expected.workspace_id {
        errors.push(scope_error("/scope/workspace_id", "workspace mismatch"));
    }
    if actual.run_id != expected.run_id {
        errors.push(scope_error("/scope/run_id", "run mismatch"));
    }
    if actual.agent_id != expected.agent_id {
        errors.push(scope_error("/scope/agent_id", "agent mismatch"));
    }
}

fn validate_value_limits(value: &Value, byte_limit: usize) -> Result<(), ValidationError> {
    walk_limits(value, 1)?;
    if canonical_json_bytes(value)?.len() > byte_limit {
        return Err(limit("canonical byte ceiling exceeded"));
    }
    Ok(())
}

fn validate_limits_ref(reference: &ProtocolLimitsRef) -> Result<(), ValidationError> {
    if reference.profile == "protocol-limits-v1"
        && reference.digest.as_str() == ProtocolLimitsV1::DIGEST
    {
        Ok(())
    } else {
        Err(ValidationError::new(
            ErrorCode::InvariantViolation,
            "/protocol_limits_ref",
            "protocol_limits_v1",
            "limits profile identity is not the exact supported V1 reference",
        ))
    }
}

fn walk_limits(value: &Value, depth: usize) -> Result<(), ValidationError> {
    if depth > ProtocolLimitsV1::DEPTH {
        return Err(limit("nesting depth exceeded"));
    }
    match value {
        Value::String(value) if value.len() > ProtocolLimitsV1::STRING_BYTES => {
            Err(limit("decoded string byte ceiling exceeded"))
        }
        Value::Array(values) => {
            if values.len() > ProtocolLimitsV1::COLLECTION {
                return Err(limit("array element ceiling exceeded"));
            }
            for value in values {
                walk_limits(value, depth + 1)?;
            }
            Ok(())
        }
        Value::Object(values) => {
            if values.len() > ProtocolLimitsV1::COLLECTION {
                return Err(limit("object member ceiling exceeded"));
            }
            for (name, value) in values {
                if name.len() > ProtocolLimitsV1::STRING_BYTES {
                    return Err(limit("object name byte ceiling exceeded"));
                }
                walk_limits(value, depth + 1)?;
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

fn is_decimal(value: &str) -> bool {
    value == "0" || (!value.starts_with('0') && value.bytes().all(|byte| byte.is_ascii_digit()))
}

pub(crate) fn is_canonical_timestamp(value: &str) -> bool {
    let bytes = value.as_bytes();
    let shape = bytes.len() == 24
        && bytes[4] == b'-'
        && bytes[7] == b'-'
        && bytes[10] == b'T'
        && bytes[13] == b':'
        && bytes[16] == b':'
        && bytes[19] == b'.'
        && bytes[23] == b'Z'
        && bytes.iter().enumerate().all(|(index, byte)| {
            matches!(index, 4 | 7 | 10 | 13 | 16 | 19 | 23) || byte.is_ascii_digit()
        });
    if !shape {
        return false;
    }
    let number = |start: usize, end: usize| value[start..end].parse::<u32>().ok();
    let (Some(year), Some(month), Some(day), Some(hour), Some(minute), Some(second), Some(_millis)) = (
        number(0, 4),
        number(5, 7),
        number(8, 10),
        number(11, 13),
        number(14, 16),
        number(17, 19),
        number(20, 23),
    ) else {
        return false;
    };
    let leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
    let max_day = match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if leap => 29,
        2 => 28,
        _ => return false,
    };
    day >= 1 && day <= max_day && hour <= 23 && minute <= 59 && second <= 59
}

fn sort_and_truncate(errors: &mut Vec<ValidationError>) {
    errors.sort_by(|left, right| {
        left.path
            .cmp(&right.path)
            .then_with(|| format!("{:?}", left.code).cmp(&format!("{:?}", right.code)))
    });
    errors.truncate(ProtocolLimitsV1::ERRORS);
}

fn scope_error(path: &str, detail: &str) -> ValidationError {
    ValidationError::new(
        ErrorCode::ScopeMismatch,
        path,
        "trusted_validation_context",
        detail,
    )
}
fn schema_error(path: &str, detail: &str) -> ValidationError {
    ValidationError::new(ErrorCode::SchemaMismatch, path, "schema_set", detail)
}
fn limit(detail: &str) -> ValidationError {
    ValidationError::new(ErrorCode::LimitExceeded, "", "protocol_limits_v1", detail)
}
fn invariant(detail: &str) -> ValidationError {
    ValidationError::new(ErrorCode::InvariantViolation, "", "protocol", detail)
}

struct UniqueValueVisitor;

impl<'de> Visitor<'de> for UniqueValueVisitor {
    type Value = Value;

    fn expecting(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str("a JSON value without duplicate object keys")
    }
    fn visit_bool<E: serde::de::Error>(self, value: bool) -> Result<Value, E> {
        Ok(Value::Bool(value))
    }
    fn visit_i64<E: serde::de::Error>(self, value: i64) -> Result<Value, E> {
        Ok(Value::Number(value.into()))
    }
    fn visit_u64<E: serde::de::Error>(self, value: u64) -> Result<Value, E> {
        Ok(Value::Number(value.into()))
    }
    fn visit_f64<E: serde::de::Error>(self, _value: f64) -> Result<Value, E> {
        Err(E::custom("floating point values are forbidden"))
    }
    fn visit_str<E: serde::de::Error>(self, value: &str) -> Result<Value, E> {
        Ok(Value::String(value.to_owned()))
    }
    fn visit_string<E: serde::de::Error>(self, value: String) -> Result<Value, E> {
        Ok(Value::String(value))
    }
    fn visit_none<E: serde::de::Error>(self) -> Result<Value, E> {
        Ok(Value::Null)
    }
    fn visit_unit<E: serde::de::Error>(self) -> Result<Value, E> {
        Ok(Value::Null)
    }
    fn visit_some<D: serde::Deserializer<'de>>(self, deserializer: D) -> Result<Value, D::Error> {
        deserializer.deserialize_any(UniqueValueVisitor)
    }
    fn visit_seq<A: SeqAccess<'de>>(self, mut sequence: A) -> Result<Value, A::Error> {
        let mut values = Vec::new();
        while let Some(value) = sequence.next_element_seed(UniqueValueSeed)? {
            values.push(value);
        }
        Ok(Value::Array(values))
    }
    fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<Value, A::Error> {
        let mut values = serde_json::Map::new();
        while let Some(name) = map.next_key::<String>()? {
            if values.contains_key(&name) {
                return Err(serde::de::Error::custom("duplicate object key"));
            }
            values.insert(name, map.next_value_seed(UniqueValueSeed)?);
        }
        Ok(Value::Object(values))
    }
}

struct UniqueValueSeed;

impl<'de> serde::de::DeserializeSeed<'de> for UniqueValueSeed {
    type Value = Value;
    fn deserialize<D: serde::Deserializer<'de>>(self, deserializer: D) -> Result<Value, D::Error> {
        deserializer.deserialize_any(UniqueValueVisitor)
    }
}

#[allow(dead_code)]
fn _assert_send_sync() {
    fn check<T: Send + Sync>() {}
    check::<SchemaSet>();
    check::<ValidatedEvent>();
    check::<AgentId>();
    check::<StreamId>();
    check::<Digest>();
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;
    use crate::{EventId, ProtocolLimitsRef, RunId, SchemaDocument, TenantId, UserId};

    fn digest(hex: char) -> Digest {
        Digest::parse(format!("sha256:{}", hex.to_string().repeat(64))).unwrap()
    }
    fn document(name: &str, body: Value) -> (SchemaDocument, SchemaRef) {
        let mut object = body.as_object().cloned().unwrap();
        let id = format!("urn:pareto-harness:schema:{name}:1.0");
        object.insert("$id".to_owned(), Value::String(id.clone()));
        object.insert(
            "$schema".to_owned(),
            Value::String("https://json-schema.org/draft/2020-12/schema".to_owned()),
        );
        let value = Value::Object(object);
        let reference = SchemaRef {
            r#type: name.to_owned(),
            major: 1,
            minor: 0,
            schema_digest: digest_schema(&id, &value).unwrap(),
        };
        (
            SchemaDocument {
                filename: format!("{name}.json"),
                document: value,
            },
            reference,
        )
    }

    fn scope() -> IsolationScope {
        IsolationScope {
            tenant_id: TenantId::parse("tenant_local").unwrap(),
            user_id: Some(UserId::parse("user_alice").unwrap()),
            workspace_id: crate::WorkspaceId::parse("workspace_repo").unwrap(),
            run_id: RunId::parse("run_one").unwrap(),
            agent_id: AgentId::parse("agent_primary").unwrap(),
        }
    }

    fn admitted() -> (SchemaSet, SchemaRef, SchemaRef) {
        let (payload_doc, payload_ref) = document(
            "run-started-payload",
            json!({"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"unevaluatedProperties":false}),
        );
        let (envelope_doc, envelope_ref) = document("event-envelope", json!({"type":"object"}));
        let (manifest_doc, manifest_ref) =
            document("schema-set-manifest", json!({"type":"object"}));
        let mut schemas = vec![
            payload_ref.clone(),
            envelope_ref.clone(),
            manifest_ref.clone(),
        ];
        schemas.sort();
        let manifest = SchemaSetManifest {
            schemas,
            event_envelope_schema_ref: envelope_ref.clone(),
            event_bindings: vec![EventTypeBinding {
                event_type: "run-started".to_owned(),
                major: 1,
                minor: 0,
                payload_schema_ref: payload_ref.clone(),
                variant_id: "run-started-v1".to_owned(),
            }],
        };
        let reference = SchemaSetRef {
            manifest_digest: digest_json(
                "schema-set",
                &manifest_ref,
                &serde_json::to_value(&manifest).unwrap(),
            )
            .unwrap(),
            manifest_schema_ref: manifest_ref,
        };
        let authority = SchemaAdmissionAuthority::kernel_owned();
        let set = SchemaSet::admit(
            &authority,
            manifest,
            vec![payload_doc, envelope_doc, manifest_doc],
            &reference,
        )
        .unwrap();
        (set, payload_ref, envelope_ref)
    }

    fn valid_event(
        set: &SchemaSet,
        payload_ref: SchemaRef,
        envelope_ref: SchemaRef,
    ) -> (EventEnvelope, TrustedValidationContext) {
        let payload = json!({"message":"started"});
        let limits = ProtocolLimitsRef {
            profile: "protocol-limits-v1".to_owned(),
            digest: Digest::parse(ProtocolLimitsV1::DIGEST).unwrap(),
        };
        let context = set.trusted_context(
            scope(),
            AgentId::parse("agent_primary").unwrap(),
            StreamId::parse("stream_run-one").unwrap(),
            limits,
        );
        let event = EventEnvelope {
            schema_ref: envelope_ref,
            scope: scope(),
            event_id: EventId::parse("event_one").unwrap(),
            stream_id: StreamId::parse("stream_run-one").unwrap(),
            run_id: RunId::parse("run_one").unwrap(),
            sequence: "1".to_owned(),
            causation_id: None,
            correlation_id: "corr-one".to_owned(),
            event_type: "run-started".to_owned(),
            event_major: 1,
            event_minor: 0,
            occurred_at: "2026-08-22T10:11:12.123Z".to_owned(),
            actor: AgentId::parse("agent_primary").unwrap(),
            payload_digest: digest_json("event-payload", &payload_ref, &payload).unwrap(),
            payload_schema_ref: payload_ref,
            payload,
        };
        (event, context)
    }

    #[test]
    fn bootstrap_rejects_self_signed_or_missing_member_bytes() {
        let bundle = crate::generate_schema_bundle().unwrap();
        assert!(
            SchemaSet::bootstrap_initial(
                bundle.manifest.clone(),
                bundle.schemas.clone(),
                &bundle.reference,
            )
            .is_ok()
        );
        let authority = SchemaAdmissionAuthority::kernel_owned();
        assert!(
            SchemaSet::admit(
                &authority,
                bundle.manifest.clone(),
                Vec::new(),
                &bundle.reference
            )
            .is_err()
        );
        let mut wrong = bundle.reference.clone();
        wrong.manifest_digest = digest('f');
        assert!(SchemaSet::admit(&authority, bundle.manifest, bundle.schemas, &wrong).is_err());
    }

    #[test]
    fn isolation_boundaries_and_payload_schema_fail_closed() {
        let (set, payload_ref, envelope_ref) = admitted();
        let (event, context) = valid_event(&set, payload_ref, envelope_ref);
        assert!(set.validate_event(event.clone(), &context).is_ok());
        for mutate in 0..5 {
            let mut candidate = event.clone();
            match mutate {
                0 => candidate.sequence.clear(),
                1 => candidate.payload = json!({"wrong":true}),
                2 => {
                    candidate.scope.workspace_id =
                        crate::WorkspaceId::parse("workspace_other").unwrap()
                }
                3 => candidate.actor = AgentId::parse("agent_other").unwrap(),
                _ => candidate.schema_ref.r#type = "evidence-record".to_owned(),
            }
            if mutate == 1 {
                candidate.payload_digest = digest_json(
                    "event-payload",
                    &candidate.payload_schema_ref,
                    &candidate.payload,
                )
                .unwrap();
                let errors = set.validate_event(candidate, &context).unwrap_err();
                assert!(
                    errors
                        .iter()
                        .any(|error| error.path.starts_with("/payload"))
                );
            } else {
                assert!(set.validate_event(candidate, &context).is_err());
            }
        }
        let mut wrong_limits = context;
        wrong_limits.protocol_limits_ref.digest = digest('d');
        assert!(set.validate_event(event, &wrong_limits).is_err());
    }

    #[test]
    fn errors_are_sorted_and_truncated_without_payload_echo() {
        let mut errors: Vec<_> = (0..40)
            .rev()
            .map(|index| {
                ValidationError::new(
                    ErrorCode::SchemaMismatch,
                    &format!("/payload/{index:02}"),
                    "schema_set",
                    "safe summary",
                )
            })
            .collect();
        sort_and_truncate(&mut errors);
        assert_eq!(errors.len(), ProtocolLimitsV1::ERRORS);
        assert!(errors.windows(2).all(|pair| pair[0].path <= pair[1].path));
        assert!(errors.iter().all(|error| error.detail == "safe summary"));
    }
}
